### ISSUE TITLE
preventing unauthorised access to proxy server 

### ISSUE THREAD

**Issue by dsplog** [simonplend/example-nodejs-api-proxy-server#1]
Thanks for the code. Question coming to mind is : 
- url of the proxy server is exposed in the javascript
- given so, unauthorised users can still call the proxy server api and get results. 

How do we protect against that ?

**Comment by simonplend** [comment]
[The article](https://simonplend.com/how-to-securely-call-an-authenticated-api-from-your-front-end/) that this code is for intentionally *doesn't* cover restricting access to the proxy server.

`fastify-http-proxy` has a [preHandler](https://github.com/fastify/fastify-http-proxy#prehandler) option that allows you to define a function to run for every request before it is sent to the upstream server. You could implement an authorization check of some kind there, for example by verifying a [JSON Web Token](https://jwt.io/) (JWT). There's a Fastify plugin if you decide to go down that route: [@fastify/jwt](https://github.com/fastify/fastify-jwt).

**Comment by dsplog** [comment]
thanks @simonplend . this helps. 

on a related note, will look forward to any article from you on best practises  (with some code snippets) on restricting access to proxy server.
